### PR TITLE
Wav2Vec2 ONNX

### PR DESCRIPTION
**Pull request by vasudevgupta7**
@sayakpaul, I prepared a notebook showing how TF Wav2Vec2 model can be exported in ONNX. Do you think we can include this notebook as well. Here is the [link to notebook](https://colab.research.google.com/github/vasudevgupta7/gsoc-wav2vec2/blob/deploy/notebooks/wav2vec2_onnx.ipynb).

I will add text to to this notebook if you approve. `ONNX exported model` is reducing latency by `more than 50%` as compared to `tf.function() wrapped model` on CPU (comparing time on CPU as deployment commonly happens on CPUs).

### CODE REVIEW

**Comment by sayakpaul** [comment]
Looks great. Yes, we should absolutely do this. Here are a couple more suggestions with regards to running optimizer inference:

* Let's make a detailed note in the README about running wav2vec2 and the fine-tuned models on different hardware setups. GPU, CPU, etc. What I mean is users should be instructed about which tooling to use when running on say, CPU. 
* Is the self-supervised model good for any inference tasks? I guess when it's fine-tuned on a downstream task like speech-to-text, then it becomes more useful w.r.t running inference. In that case, we should also include the ONNX version of the LibriSpeech model. Please correct me if I am wrong. 
* While we are on this topic, I wouldn't mind taking the first pass on converting the LibriSpeech model to TFLite and benchmarking it. TFLite provides a [handy benchmarking tool](https://www.tensorflow.org/lite/performance/measurement) that allows you to know details about the inference latency on your mobile phone. 
* If you want we can also work (after GSoC) on distilling the models into smaller ones so that they run well sufficiently fast without compromising the performance.

**Comment by vasudevgupta7** [comment]
> * Is the self-supervised model good for any inference tasks? I guess when it's fine-tuned on a downstream task like speech-to-text, then it becomes more useful w.r.t running inference. In that case, we should also include the ONNX version of the LibriSpeech model. Please correct me if I am wrong.

I am using Wav2Vec2ForCTC already (it's the fine-tuned model; using converted fine-tuned weights) and it can be directly used for inference. I will show decoding part also in the notebook.

> * While we are on this topic, I wouldn't mind taking the first pass on converting the LibriSpeech model to TFLite and benchmarking it. TFLite provides a [handy benchmarking tool](https://www.tensorflow.org/lite/performance/measurement) that allows you to know details about the inference latency on your mobile phone.

I tried that TFLite a bit. Model size is not decreasing and remaining 400 MB but I need to try this more stuff on this. Will keep you posted on this.

> * If you want we can also work (after GSoC) on distilling the models into smaller ones so that they run well sufficiently fast without compromising the performance.

Definitely!!

**Comment by sayakpaul** [comment]
> I tried that TFLite a bit. Model size is not decreasing and remaining 400 MB but I need to try this more stuff on this. Will keep you posted on this.

Probably you might have forgotten to specify the quantization method. [This page](https://www.tensorflow.org/lite/performance/post_training_quantization) provides a nice overview.

**Comment by vasudevgupta7** [comment]
@sayakpaul, @MorganR, [onnx-notebook](https://colab.research.google.com/github/vasudevgupta7/gsoc-wav2vec2/blob/deploy/notebooks/wav2vec2_onnx.ipynb) is ready for review.

Thanks!!

**Comment by sayakpaul** [comment]
The notebook looks good @vasudevgupta7. 

I am a bit skeptical about the JIT runtime, though. Could it be that the time reported involves the initial JIT library binding time? If so, that is usually not counted and is considered under warm-ups. 

I'd first run dummy inferences in order to make sure things are warmed up sufficiently. And then I'd run the actual inference for benchmarking.

**Comment by vasudevgupta7** [comment]
> I am a bit skeptical about the JIT runtime, though. Could it be that the time reported involves the initial JIT library binding time? If so, that is usually not counted and is considered under warm-ups.
> 
> I'd first run dummy inferences in order to make sure things are warmed up sufficiently. And then I'd run the actual inference for benchmarking.

@sayakpaul I am warming it up already (before benchmarking) in following cell:
```python
import numpy as np

onnx_outputs = session.run(None, {"speech": speech.numpy()})[0]
tf_outputs = jitted_forward(speech)

assert np.allclose(onnx_outputs, tf_outputs.numpy(), atol=1e-2)
```

Also, If one runs the last cell again & again, he will observe that he will get very similar time to what is shown in Colab

**Comment by vasudevgupta7** [comment]
Merging this PR :)

**Pull request merged**
